language: node_js

env:
  - NODE_ENV=test CXX=g++-4.8

node_js:
  - "5.3.0"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres

install:
  - npm install

script:
  - npm run knex migrate:latest
  - npm run knex seed:run
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  on:
    branch: master
  app: testing-travis
  run:
    - "npm run knex migrate:latest"
